### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by crealx** [agentejo/Detektivo#2]
Thank you for this addon...
But, I'm a bit lost...
I upload the addon on cockpit... I go to settings > Addons, and I only see a block with Detektivo...
How can I active it ?
Where must I put the config file ?

Can you help me a bit ?

Thanks !

**Comment by mares29** [comment]
Hi, put detektivo.yam into /config folder.
Don't forget to define collections and fields in the config file.

**Comment by crealx** [comment]
Hi... Thank you for your answer.
I created detektivo.yam file into modules/addons/detektivo/config
I put this on it :
`collections:
    vinyle: [titre, artiste]`
Where vinyle is my collection and title and artist my fields.
And now ? I can't find a way to display my search ?

Thank you !!

**Comment by crealx** [comment]
detekctivo.yaml, sorry !

**Comment by kamarkiewicz** [comment]
Look at [my setup](https://github.com/kamarkiewicz/Strona_KSI/tree/master/backend).
I configured Detektivo in `config/detektivo.yaml` and it kinda works (it indexes collections). I don't know how to make a query either. I asked about this in other issue #3

**Comment by aheinze** [comment]
https://github.com/agentejo/Detektivo/blob/master/README.md#api

**Comment by roddyka** [comment]
Hey guys, how are you?
Here in my TNTSeaech.php on search function we have 3 parameters, $index its my collection, i have $query and its my "search" and i have $options... what is this?

And i have other question: if i save a post with this title "paralelepipedo" i cant found just writing "parale" i need write the complete sentence how can i change it? 

Thanks
