### ISSUE TITLE
API spec

### ISSUE THREAD

**Issue by kamarkiewicz** [agentejo/Detektivo#3]
Hello,
I would like to use this plugin with Cockpit CMS Next. I managed to install the addon, but don't know how to get to REST API of client provided query. My configuration:
```
engine: tntsearch
collections:
    posts: [title, excerpt, content]
```
Reading this project's php files it looks like there is no single REST endpoint, that is registered at `/api`. How to make a query?

**Comment by kamarkiewicz** [comment]
I found an alternative approach to create a full-text search on a website (but it doesn't use Detektivo): https://github.com/agentejo/cockpit/issues/705#issuecomment-385174932

**Comment by aheinze** [comment]
https://github.com/agentejo/Detektivo/blob/master/README.md#api
